### ISSUE TITLE
"Delete entry" permissions for Admin

### ISSUE THREAD

**Issue by malakyeshort** [WebDevJBR/volunteer-points-log#188]
Currently there is no way for an admin to delete either a time entry or a volunteer that is entered. 
Low priority since there are work arounds, but would be helpful.

**Comment by lukesample** [comment]
There is currently a way to delete a time entry for a volunteer when logged in as a User instead of admin.  The trash can on the Time Entry row is used to delete the time entry.

![image](https://user-images.githubusercontent.com/38770659/150221195-0f782ea0-f4f0-40f9-98a0-f0e5e252675e.png)
![image](https://user-images.githubusercontent.com/38770659/150221258-4531683d-72ed-4070-98e2-1f6cfc203476.png)

**Comment by malakyeshort** [comment]
When I get to the "Are you sure you want to delete this row?" question, the checkmark to verify is greyed out and I'm unable to click it.

**Comment by lukesample** [comment]
Its possible that the validation being messed up from Issue #187 was causing the check box to be disabled.  I took that screenshot after I fixed it.

**Comment by lukesample** [comment]
Looks like my suspicion is correct.  Just tried it without my fix for #187 and it doesn't work.

Closed by PR #194

**Comment by lukesample** [comment]
Misunderstood issue.  Asking for new feature, not reporting a bug.
